version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /src/docker-compose/mysql
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /src/docker-compose/redis
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /src/docker-compose/mongo
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /src/docker-compose/grafana
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /src/docker-compose/prometheus
    schedule:
      interval: weekly
